"""
applications/jobs/_template/job_info.py
========================================
Template for a new job application bundle.
Auto-generated by `scripts/new_application.py`.
Manually fill in the fields after reviewing the job posting.

This file is read by `scripts/track.py log` to pre-fill tracker.csv.
"""

# ── Identity ─────────────────────────────────────────────────────────────────
JOB_ID   = "_template"
COMPANY  = "Company Name"
ROLE     = "Role Title"

# ── Posting Details ───────────────────────────────────────────────────────────
PLATFORM    = ""       # LinkedIn / Indeed / Company Website / Referral / Handshake
URL         = ""       # Full URL to the job posting
JOB_ID_EXT  = None     # External req/job ID from the posting, e.g. "REQ-12345"
REFERRAL    = None     # Referrer's full name if applicable
RECRUITER   = None     # Recruiter name if known before applying

# ── Location & Logistics ─────────────────────────────────────────────────────
LOCATION       = ""    # e.g. "San Francisco, CA" or "Remote"
VISA_SPONSORED = None  # True / False / None (unknown)
SALARY_RANGE   = ""    # As listed in the posting, e.g. "$150k–$200k"
TEAM           = ""    # Team/org within company, e.g. "Google DeepMind Gemini team"

# ── Application Status ────────────────────────────────────────────────────────
# This is the ground truth; tracker.csv is updated by scripts/track.py
STATUS         = "Applied"

# ── Notes & Context ───────────────────────────────────────────────────────────
NOTES = ""

# ── JD Keywords (copy from job description) ──────────────────────────────────
# Use these to align bullet points in resume/tailoring/<id>.py.
# Cross-check against your master_data.py entries before tailoring.
KEYWORDS = [
    # "CUDA kernel optimization",
    # "PyTorch distributed training",
    # "LLM inference",
    # "MLOps",
    # "computer vision",
]

# ── Networking Targets ────────────────────────────────────────────────────────
# People to connect with at this company.
# Find via LinkedIn → see networking/strategy.md for how to approach.
NETWORKING_TARGETS = [
    # {"name": "Jane Doe", "title": "ML Engineer", "linkedin": "https://..."},
    # {"name": "John Smith", "title": "Engineering Manager", "linkedin": "https://..."},
]

# ── Interview Prep Notes ──────────────────────────────────────────────────────
# Fill in as you learn about the interview process.
INTERVIEW_FORMAT = ""   # e.g. "2 LC coding + 1 ML system design + 1 behavioral"
PREP_RESOURCES   = []   # e.g. ["NVIDIA GPU interview guide", "ML system design primer"]
